name: MiniPlaceholders-AFKPlus-OG
version: '${version}'
main: net.trueog.miniplaceholdersafkplus.MiniPlaceholdersAFKPlus
api-version: '${apiVersion}'
depend: [AFKPlus, MiniPlaceholders, Utilities-OG]
